name: final_project_app
description: "CSC 322 Starter App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

# -----------------------------------------------------------------------
# Allowed Flutter SDK Versions
# -----------------------------------------------------------------------
environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.22.0 <4.0.0"

# -----------------------------------------------------------------------
# Dependencies
# -----------------------------------------------------------------------
dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^6.0.2
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_storage: ^13.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  state_notifier: ^1.0.0
  flutter_secure_storage: ^9.2.4
  font_awesome_flutter: ^10.10.0
  go_router: ^16.2.4
  image_picker: ^1.2.0
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0
  logger: ^2.6.2
  lottie: ^3.3.2
  permission_handler: ^12.0.1
  riverpod_annotation: ^3.0.3
  graphic: ^2.6.0
  carousel_slider: ^5.1.1
  flutter_gemini: ^3.0.0

dependency_overrides:
  flutter_secure_storage_web: ^2.0.0-beta.1
  # js: ^0.6.3

# -----------------------------------------------------------------------
# Dev Dependencies
# -----------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

# -----------------------------------------------------------------------
# Icon Displayed in OS
# -----------------------------------------------------------------------
flutter_launcher_icons:
  image_path_android: "images/logo.png"
  image_path_ios: "images/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
  # riverpod_generator: ^2.4.2
  # riverpod_lint: ^2.3.12
  # flutter_lints: ^3.0.0
  # build_runner:
  # custom_lint:

# -----------------------------------------------------------------------
# Flutter Settings
# -----------------------------------------------------------------------
flutter:
  uses-material-design: true
  assets:
    - images/
    - animations/
    - assets/
    - images/wonders/
